TABGra/Models/Potwor.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TABGra.Models
{
    public class Potwor
    {
        public int id { get; set; }
        public string nazwa { get; set; }
        public string doswiadczenie { get; set; }
        public string przedmioty { get; set; }
        public virtual ICollection<Ekwipunek> ekwipunek { get; set; }
    }
}

TABGra/Controllers/EkwipuneksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TABGra.Models;

namespace TABGra.Controllers
{
    [Authorize]
    public class EkwipuneksController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Ekwipuneks
        public ActionResult Index()
        {
            return View(db.ekwipunek.ToList());
        }
        public ActionResult EkwipunekPotwor(int id)
        {
            return View(db.potwor.Find(id).ekwipunek);
        }
        public ActionResult EkwipunekGracz(int id)
        {
            return View(db.gracz.Find(id).ekwipunek);
        }
        public ActionResult Search(string search)
        {
            return View(db.ekwipunek.Where(e => e.opis.ToLower().Contains(search.ToLower())).ToList());
        }
        // GET: Ekwipuneks/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ekwipunek ekwipunek = db.ekwipunek.Find(id);
            if (ekwipunek == null)
            {
                return HttpNotFound();
            }
            return View(ekwipunek);
        }

        // GET: Ekwipuneks/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Ekwipuneks/Create
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,opis")] Ekwipunek ekwipunek)
        {
            if (ModelState.IsValid)
            {
                db.ekwipunek.Add(ekwipunek);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(ekwipunek);
        }

        // GET: Ekwipuneks/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ekwipunek ekwipunek = db.ekwipunek.Find(id);
            if (ekwipunek == null)
            {
                return HttpNotFound();
            }
            return View(ekwipunek);
        }

        // POST: Ekwipuneks/Edit/5
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,opis")] Ekwipunek ekwipunek)
        {
            if (ModelState.IsValid)
            {
                db.Entry(ekwipunek).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(ekwipunek);
        }

        // GET: Ekwipuneks/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ekwipunek ekwipunek = db.ekwipunek.Find(id);
            if (ekwipunek == null)
            {
                return HttpNotFound();
            }
            return View(ekwipunek);
        }

        // POST: Ekwipuneks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Ekwipunek ekwipunek = db.ekwipunek.Find(id);
            db.ekwipunek.Remove(ekwipunek);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TABGra/Controllers/PotworsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TABGra.Models;

namespace TABGra.Controllers
{
    [Authorize]
    public class PotworsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Potwors
        public ActionResult Index()
        {

            return View(db.potwor.ToList());
        }
        public ActionResult Search(string search)
        {
            return View(db.potwor.Where(e => e.nazwa.ToLower().Contains(search.ToLower())).ToList());
        }
        public ActionResult AddEkwipunek(int id)
        {
            List<SelectListItem> ekwipunekitems = new List<SelectListItem>();

            var ekwipunek = db.ekwipunek.ToList();
            foreach (var ll in ekwipunek)
            {
                ekwipunekitems.Add(new SelectListItem
                {
                    Text = ll.opis,
                    Value = ll.id.ToString()
                });
            }
            ViewBag.ekwipunek = ekwipunekitems;

            return View(db.potwor.Find(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddEkwipunek([Bind(Include = "id,nazwa")] Potwor potwor)
        {
            int ekwipunekid = Int32.Parse(Request.Form["ekwipunekSelected"].ToString());
            Potwor p = db.potwor.Find(potwor.id);
            p.ekwipunek.Add(db.ekwipunek.Find(ekwipunekid));
            if (ModelState.IsValid)
            {
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(potwor);
        }
        public ActionResult DeleteEkwipunek(int id)
        {
            List<SelectListItem> ekwipunekitems = new List<SelectListItem>();

            var ekwipunek = db.potwor.Find(id).ekwipunek;

            foreach (var ll in ekwipunek)
            {
                ekwipunekitems.Add(new SelectListItem
                {
                    Text = ll.opis,
                    Value = ll.id.ToString()
                });
            }
            ViewBag.ekwipunek = ekwipunekitems;

            return View(db.potwor.Find(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteEkwipunek([Bind(Include = "id,nazwa")] Potwor potwor)
        {
            int ekwipunekid = Int32.Parse(Request.Form["ekwipunekSelected"].ToString());
            Potwor p = db.potwor.Find(potwor.id);
            p.ekwipunek.Remove(db.ekwipunek.Find(ekwipunekid));
            if (ModelState.IsValid)
            {
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(potwor);
        }
        // GET: Potwors/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Potwor potwor = db.potwor.Find(id);
            if (potwor == null)
            {
                return HttpNotFound();
            }
            return View(potwor);
        }

        // GET: Potwors/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Potwors/Create
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,nazwa,doswiadczenie,przedmioty")] Potwor potwor)
        {
            if (ModelState.IsValid)
            {
                db.potwor.Add(potwor);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(potwor);
        }

        // GET: Potwors/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Potwor potwor = db.potwor.Find(id);
            if (potwor == null)
            {
                return HttpNotFound();
            }
            return View(potwor);
        }

        // POST: Potwors/Edit/5
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,nazwa,doswiadczenie,przedmioty")] Potwor potwor)
        {
            if (ModelState.IsValid)
            {
                db.Entry(potwor).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(potwor);
        }

        // GET: Potwors/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Potwor potwor = db.potwor.Find(id);
            if (potwor == null)
            {
                return HttpNotFound();
            }
            return View(potwor);
        }

        // POST: Potwors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Potwor potwor = db.potwor.Find(id);
            db.potwor.Remove(potwor);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TABGra/Views/Potwors/AddEkwipunek.cshtml
@model TABGra.Models.Potwor

@{
    ViewBag.Title = "Dodaj Ekwipunek";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Dodawanie Ekwipunku</h2>
@{
    var getlistE = ViewBag.ekwipunek as IEnumerable<SelectListItem>;
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Potwor</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.nazwa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nazwa, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
                @Html.ValidationMessageFor(model => model.nazwa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Wibierz ekwipunek", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ekwipunekSelected", getlistE, new { @class = "css-class" })
            </div>

        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Zapisz" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TABGra/Views/Potwors/Create.cshtml
@model TABGra.Models.Potwor

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Potwor</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.nazwa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nazwa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nazwa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.doswiadczenie, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.doswiadczenie, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.doswiadczenie, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.przedmioty, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.przedmioty, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.przedmioty, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TABGra/Views/Potwors/Delete.cshtml
@model TABGra.Models.Potwor

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Potwor</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nazwa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nazwa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.doswiadczenie)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.doswiadczenie)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.przedmioty)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.przedmioty)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

TABGra/Views/Potwors/DeleteEkwipunek.cshtml
@model TABGra.Models.Potwor

@{
    ViewBag.Title = "Usuwanie Ekwipunek";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Usuwanie Ekwipunku</h2>
@{
    var getlistE = ViewBag.ekwipunek as IEnumerable<SelectListItem>;
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Potwor</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.nazwa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nazwa, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
                @Html.ValidationMessageFor(model => model.nazwa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Wibierz ekwipunek", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ekwipunekSelected", getlistE, new { @class = "css-class" })
            </div>

        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Zapisz" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TABGra/Views/Potwors/Details.cshtml
@model TABGra.Models.Potwor

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Potwor</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nazwa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nazwa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.doswiadczenie)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.doswiadczenie)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.przedmioty)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.przedmioty)
        </dd>

        <dt>
            @Html.ActionLink("Ekwipunek", "EkwipunekPotwor", "Ekwipuneks", new { id = Model.id }, null)
        </dt>

        <dd>
            @foreach(var ek in Model.ekwipunek){
                
                <p>
                    @ek.opis
                </p>
            }
            <p>@Html.ActionLink("Dodaj Ekiwpunek", "AddEkwipunek", "Potwors", new { id = Model.id }, new { @class = "btn btn-default" })</p> 
            <p>@Html.ActionLink("Usun Ekiwpunek", "DeleteEkwipunek", "Potwors", new { id = Model.id }, new { @class = "btn btn-default" })</p> 
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

TABGra/Views/Potwors/Edit.cshtml
@model TABGra.Models.Potwor

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Potwor</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.nazwa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nazwa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nazwa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.doswiadczenie, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.doswiadczenie, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.doswiadczenie, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.przedmioty, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.przedmioty, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.przedmioty, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TABGra/Views/Potwors/Index.cshtml
@model IEnumerable<TABGra.Models.Potwor>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Potwor</h2>
<form method="get" action="@Url.Action("Search", "Potwors")">
    <label for="search">Wyszukiwanie po nazwie</label>
    <input type="text" name="search" id="search" />
    <button type="submit">Wyszukaj</button>
</form>
<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.nazwa)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.doswiadczenie)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.przedmioty)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.nazwa)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.doswiadczenie)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.przedmioty)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.id }) |
            @Html.ActionLink("Details", "Details", new { id=item.id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.id })
        </td>
    </tr>
}

</table>

TABGra/Views/Potwors/Search.cshtml
@model IEnumerable<TABGra.Models.Potwor>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Potwor</h2>
<form method="get" action="@Url.Action("Search", "Potwors")">
    <label for="search">Wyszukiwanie po nazwie</label>
    <input type="text" name="search" id="search" />
    <button type="submit">Wyszukaj</button>
</form>
<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.nazwa)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.doswiadczenie)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.przedmioty)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.nazwa)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.doswiadczenie)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.przedmioty)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.id }) |
            @Html.ActionLink("Details", "Details", new { id=item.id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.id })
        </td>
    </tr>
}

</table>