TABGra/Controllers/GraczsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TABGra.Models;

namespace TABGra.Controllers
{
    [Authorize]
    public class GraczsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Graczs
        public ActionResult Index()
        {
            return View(db.gracz.ToList());
        }
        public ActionResult Search(string search)
        {
            return View(db.gracz.Where(e => e.nazwa.ToLower().Contains(search.ToLower())).ToList());
        }
        public ActionResult SerwerGracze(int id)
        {
            return View(db.gracz.Where(g=>g.serwer.id==id).ToList());
        }

        public ActionResult AddEkwipunek(int id)
        {
            List<SelectListItem> ekwipunekitems = new List<SelectListItem>();

            var ekwipunek = db.ekwipunek.ToList();
            foreach (var ll in ekwipunek)
            {
                ekwipunekitems.Add(new SelectListItem
                {
                    Text = ll.opis,
                    Value = ll.id.ToString()
                });
            }
            ViewBag.ekwipunek = ekwipunekitems;

            return View(db.gracz.Find(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddEkwipunek([Bind(Include = "id,nazwa")] Gracz gracz)
        {
            int ekwipunekid = Int32.Parse(Request.Form["ekwipunekSelected"].ToString());
            Gracz p = db.gracz.Find(gracz.id);
            p.ekwipunek.Add(db.ekwipunek.Find(ekwipunekid));
            if (ModelState.IsValid)
            {
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(gracz);
        }
        public ActionResult DeleteEkwipunek(int id)
        {
            List<SelectListItem> ekwipunekitems = new List<SelectListItem>();

            var ekwipunek = db.gracz.Find(id).ekwipunek;

            foreach (var ll in ekwipunek)
            {
                ekwipunekitems.Add(new SelectListItem
                {
                    Text = ll.opis,
                    Value = ll.id.ToString()
                });
            }
            ViewBag.ekwipunek = ekwipunekitems;

            return View(db.gracz.Find(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteEkwipunek([Bind(Include = "id,nazwa")] Gracz gracz)
        {
            int ekwipunekid = Int32.Parse(Request.Form["ekwipunekSelected"].ToString());
            Gracz p = db.gracz.Find(gracz.id);
            p.ekwipunek.Remove(db.ekwipunek.Find(ekwipunekid));
            if (ModelState.IsValid)
            {
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(gracz);
        }


        // GET: Graczs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Gracz gracz = db.gracz.Find(id);
            if (gracz == null)
            {
                return HttpNotFound();
            }
            return View(gracz);
        }

        // GET: Graczs/Create
        public ActionResult Create()
        {
            List<SelectListItem> serweritems = new List<SelectListItem>();

            var serwer = db.serwer.ToList();
            foreach (var ll in serwer)
            {
                serweritems.Add(new SelectListItem
                {
                    Text = ll.nazwa,
                    Value = ll.id.ToString()
                });
            }
            ViewBag.serwer = serweritems;

            List<SelectListItem> Gildiaitems = new List<SelectListItem>();
            Gildiaitems.Add(new SelectListItem
            {
                Text = "brak",
                Value = "-1"
            });
            var gildia = db.gildia.ToList();
            foreach (var ll in gildia)
            {
                Gildiaitems.Add(new SelectListItem
                {
                    Text = ll.nazwa,
                    Value = ll.id.ToString()
                });
            }
            ViewBag.gildia = Gildiaitems;
            return View();
        }

        // POST: Graczs/Create
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,nazwa,doswiadczenie,sila,zycia,poziom")] Gracz gracz)
        {
            int serwerid = Int32.Parse(Request.Form["serwerSelected"].ToString());
            int gildiaid = Int32.Parse(Request.Form["gildiaSelected"].ToString());
            gracz.serwer = db.serwer.Find(serwerid);
            gracz.gildia = db.gildia.Find(gildiaid);
            if (ModelState.IsValid)
            {
                db.gracz.Add(gracz);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(gracz);
        }

        // GET: Graczs/Edit/5
        public ActionResult Edit(int? id)
        {
            List<SelectListItem> serweritems = new List<SelectListItem>();

            var serwer = db.serwer.ToList();
            foreach (var ll in serwer)
            {
                serweritems.Add(new SelectListItem
                {
                    Text = ll.nazwa,
                    Value = ll.id.ToString()
                });
            }
            ViewBag.serwer = serweritems;

            List<SelectListItem> Gildiaitems = new List<SelectListItem>();
            Gildiaitems.Add(new SelectListItem
            {
                Text = "brak",
                Value = "-1"
            });
            var gildia = db.gildia.ToList();
            foreach (var ll in gildia)
            {
                Gildiaitems.Add(new SelectListItem
                {
                    Text = ll.nazwa,
                    Value = ll.id.ToString()
                });
            }
            ViewBag.gildia = Gildiaitems;

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Gracz gracz = db.gracz.Find(id);
            if (gracz == null)
            {
                return HttpNotFound();
            }
            return View(gracz);
        }

        // POST: Graczs/Edit/5
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,nazwa,doswiadczenie,sila,zycia,poziom")] Gracz gracz)
        {
            int serwerid = Int32.Parse(Request.Form["serwerSelected"].ToString());
            int gildiaid = Int32.Parse(Request.Form["gildiaSelected"].ToString());
            Gracz ng = db.gracz.Find(gracz.id);
            ng.nazwa = gracz.nazwa;
            ng.doswiadczenie = gracz.doswiadczenie;
            ng.sila = gracz.sila;
            ng.zycia = gracz.zycia;
            ng.poziom = gracz.poziom;
            ng.serwer = db.serwer.Find(serwerid);
            ng.gildia = db.gildia.Find(gildiaid);

            if (ModelState.IsValid)
            {
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(gracz);
        }

        // GET: Graczs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Gracz gracz = db.gracz.Find(id);
            if (gracz == null)
            {
                return HttpNotFound();
            }
            return View(gracz);
        }

        // POST: Graczs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Gracz gracz = db.gracz.Find(id);
            db.gracz.Remove(gracz);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        #region zadanie

        public ActionResult GraczeZadanie(int id)
        {
            return View(db.umiejetnosci.Find(id).gracze);
        }
        public ActionResult AddZadanie(int id)
        {
            List<SelectListItem> zadanieitem = new List<SelectListItem>();

            var zadanie = db.zadanie.ToList();
            foreach (var ll in zadanie)
            {
                zadanieitem.Add(new SelectListItem
                {
                    Text = ll.opis,
                    Value = ll.id.ToString()
                });
            }
            ViewBag.zadanie = zadanieitem;

            return View(db.gracz.Find(id));
        }
        public ActionResult DeleteZadanie(int id)
        {
            List<SelectListItem> zadanieitems = new List<SelectListItem>();

            var zadanie = db.gracz.Find(id).zadania;

            foreach (var ll in zadanie)
            {
                zadanieitems.Add(new SelectListItem
                {
                    Text = ll.opis,
                    Value = ll.id.ToString()
                });
            }
            ViewBag.zadanie = zadanieitems;

TABGra/Controllers/ZadaniesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TABGra.Models;

namespace TABGra.Controllers
{
    [Authorize]
    public class ZadaniesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Zadanies
        public ActionResult Index()
        {
            return View(db.zadanie.ToList());
        }
        public ActionResult ZadanieGracza(int id)
        {
            return View(db.gracz.Find(id).zadania);
        }
        public ActionResult Search(string search)
        {
            return View(db.zadanie.Where(e => e.opis.ToLower().Contains(search.ToLower())).ToList());
        }
        // GET: Zadanies/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Zadanie zadanie = db.zadanie.Find(id);
            if (zadanie == null)
            {
                return HttpNotFound();
            }
            return View(zadanie);
        }

        // GET: Zadanies/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Zadanies/Create
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,opis,nagroda,NPC")] Zadanie zadanie)
        {
            if (ModelState.IsValid)
            {
                db.zadanie.Add(zadanie);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(zadanie);
        }

        // GET: Zadanies/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Zadanie zadanie = db.zadanie.Find(id);
            if (zadanie == null)
            {
                return HttpNotFound();
            }
            return View(zadanie);
        }

        // POST: Zadanies/Edit/5
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,opis,nagroda,NPC")] Zadanie zadanie)
        {
            if (ModelState.IsValid)
            {
                db.Entry(zadanie).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(zadanie);
        }

        // GET: Zadanies/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Zadanie zadanie = db.zadanie.Find(id);
            if (zadanie == null)
            {
                return HttpNotFound();
            }
            return View(zadanie);
        }

        // POST: Zadanies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Zadanie zadanie = db.zadanie.Find(id);
            db.zadanie.Remove(zadanie);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TABGra/Views/Zadanies/Create.cshtml
@model TABGra.Models.Zadanie

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Stworz</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Zadanie</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.opis, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.opis, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.opis, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nagroda, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nagroda, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nagroda, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NPC, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NPC, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NPC, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TABGra/Views/Zadanies/Delete.cshtml
@model TABGra.Models.Zadanie

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Usun</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Zadanie</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.opis)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.opis)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.nagroda)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nagroda)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NPC)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NPC)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

TABGra/Views/Zadanies/Details.cshtml
@model TABGra.Models.Zadanie

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Szczegóły</h2>

<div>
    <h4>Zadanie</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.opis)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.opis)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.nagroda)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nagroda)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NPC)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NPC)
        </dd>
        <dt>
            @Html.ActionLink("Gracze", "GraczeZadanie", "Graczs", new { id = Model.id }, null)
        </dt>

        <dd>
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

TABGra/Views/Zadanies/Edit.cshtml
@model TABGra.Models.Zadanie

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edycja</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Zadanie</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.opis, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.opis, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.opis, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nagroda, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nagroda, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nagroda, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NPC, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NPC, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NPC, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TABGra/Views/Zadanies/Index.cshtml
@model IEnumerable<TABGra.Models.Zadanie>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Zadania</h2>
<form method="get" action="@Url.Action("Search", "Zadanies")">
    <label for="search">Wyszukiwanie po opisie</label>
    <input type="text" name="search" id="search" />
    <button type="submit">Wyszukaj</button>
</form>
<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.opis)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.nagroda)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NPC)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.opis)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.nagroda)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NPC)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.id }) |
            @Html.ActionLink("Details", "Details", new { id=item.id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.id })
        </td>
    </tr>
}

</table>

TABGra/Views/Zadanies/Search.cshtml
@model IEnumerable<TABGra.Models.Zadanie>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Zadania</h2>
<form method="get" action="@Url.Action("Search", "Zadanies")">
    <label for="search">Wyszukiwanie po opisie</label>
    <input type="text" name="search" id="search" />
    <button type="submit">Wyszukaj</button>
</form>
<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.opis)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.nagroda)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NPC)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.opis)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.nagroda)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NPC)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.id }) |
            @Html.ActionLink("Details", "Details", new { id=item.id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.id })
        </td>
    </tr>
}

</table>

TABGra/Views/Zadanies/ZadanieGracza.cshtml
@model IEnumerable<TABGra.Models.Zadanie>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Zadania gracza</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.opis)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.nagroda)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NPC)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.opis)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.nagroda)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NPC)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.id }) |
            @Html.ActionLink("Details", "Details", new { id=item.id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.id })
        </td>
    </tr>
}

</table>